from contextlib import asynccontextmanager

import logging

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.httpsredirect import HTTPSRedirectMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from fastapi.responses import JSONResponse
from fastapi.encoders import jsonable_encoder
from fastapi.staticfiles import StaticFiles
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.api.routes import assets, combat, diagnostics, entities, ftp, health, map, servers, websocket as websocket_routes
from app.core.logging import configure_logging
from app.core.config import get_settings
from app.core.middleware import (
    RateLimitMiddleware,
    RequestIdMiddleware,
    SecurityHeadersMiddleware,
    UnhandledExceptionMiddleware,
)

logger = logging.getLogger(__name__)
settings = get_settings()


@asynccontextmanager
async def lifespan(_: FastAPI):
    configure_logging()
    logger.info(
        "Browser security configured: environment=%s cors_enabled=%s origins_count=%d "
        "credentials=%s methods=%s max_age=%d websocket_origin_validation=true",
        settings.environment,
        settings.cors_enabled,
        len(settings.cors_origins),
        settings.cors_allow_credentials,
        ",".join(settings.allowed_methods),
        settings.cors_max_age_seconds,
    )
    from app.websocket.heartbeat import HeartbeatService
    from app.websocket.manager import connection_manager
    from app.services.event_service import event_retention_service
    heartbeat = HeartbeatService(connection_manager)
    heartbeat.start()
    event_retention_service.start()
    try:
        yield
    finally:
        from app.services.ftp import ftp_sync_manager
        await ftp_sync_manager.shutdown()
        await heartbeat.stop()
        await event_retention_service.stop()
        await connection_manager.close_all()


app = FastAPI(
    title=settings.app_name,
    version=settings.app_version,
    debug=settings.debug,
    lifespan=lifespan,
    redirect_slashes=False,
)
# Middleware is registered inside-out. CORS is added last so it can decorate
# preflight and every HTTP response, including errors generated by the inner guard.
app.add_middleware(UnhandledExceptionMiddleware)
app.add_middleware(SecurityHeadersMiddleware, settings=settings)
app.add_middleware(RateLimitMiddleware, settings=settings)
if settings.trusted_hosts != ["*"]:
    app.add_middleware(TrustedHostMiddleware, allowed_hosts=settings.trusted_hosts)
if settings.force_https:
    app.add_middleware(HTTPSRedirectMiddleware)
app.add_middleware(RequestIdMiddleware)
if settings.cors_enabled:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_origin_regex=settings.origin_regex,
        allow_credentials=settings.cors_allow_credentials,
        allow_methods=settings.allowed_methods,
        allow_headers=settings.allowed_headers,
        expose_headers=settings.exposed_headers,
        max_age=settings.cors_max_age_seconds,
    )


@app.exception_handler(RequestValidationError)
async def validation_error(_: Request, exc: RequestValidationError):
    return JSONResponse(
        jsonable_encoder({"error": "validation error", "status": 422, "details": exc.errors()}),
        status_code=422,
    )


@app.exception_handler(StarletteHTTPException)
async def http_error(_: Request, exc: StarletteHTTPException):
    return JSONResponse({"error": str(exc.detail), "status": exc.status_code}, status_code=exc.status_code, headers=exc.headers)


@app.get("/health", include_in_schema=False)
async def root_health():
    return {"status": "ok"}


app.include_router(health.router, prefix="/api/v1")
app.include_router(assets.router, prefix="/api/v1")
app.include_router(servers.router, prefix="/api/v1")
app.include_router(ftp.router, prefix="/api/v1")
app.include_router(entities.characters_router, prefix="/api/v1")
app.include_router(entities.vehicles_router, prefix="/api/v1")
app.include_router(entities.storages_router, prefix="/api/v1")
app.include_router(combat.kills_router, prefix="/api/v1")
app.include_router(combat.players_router, prefix="/api/v1")
app.include_router(map.router, prefix="/api/v1")
app.include_router(diagnostics.router, prefix="/api/v1")
app.include_router(websocket_routes.router, prefix="/api/v1")
app.mount("/static", StaticFiles(directory="app/static"), name="static")
